                css:  [ 'http://yui.yahooapis.com/2.5.2/build/reset-fonts-grids/reset-fonts-grids.css',
                        'http://yui.yahooapis.com/2.5.2/build/container/assets/skins/sam/container.css',
                        'http://yui.yahooapis.com/2.5.2/build/resize/assets/skins/sam/resize.css',
                        'http://yui.yahooapis.com/2.5.2/build/layout/assets/skins/sam/layout.css',
                        'http://yui.yahooapis.com/2.5.2/build/button/assets/skins/sam/button.css',
                        'http://yui.yahooapis.com/2.5.2/build/fonts/fonts-min.css',
                        'http://yui.yahooapis.com/2.5.2/build/tabview/assets/skins/sam/tabview.css'
                      ],
                js:   [
                        'http://yui.yahooapis.com/2.5.2/build/yahoo/yahoo-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/event/event-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/dom/dom-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/element/element-beta-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/dragdrop/dragdrop-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/container/container-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/resize/resize-beta-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/animation/animation-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/layout/layout-beta-min.js',
                        'http://yui.yahooapis.com/2.5.2/build/yahoo-dom-event/yahoo-dom-event.js',
                        'http://yui.yahooapis.com/2.5.2/build/tabview/tabview-min.js'